/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.sbsz;

import org.apache.commons.io.FileUtils;
import org.apache.maven.cli.MavenCli;

import java.io.File;
import java.io.IOException;

public class MavenLauncher {

    public static void main(String[] args) throws IOException {

        System.out.println("Launching embedded maven build system in 3,2,1 lift off!\n");

        var repo = new File("build/tmp/local-repo");
        FileUtils.deleteDirectory(repo);

        var mavenProjectDir = new File("build/resources/main/demo").getAbsolutePath();

        var cli = new MavenCli();

        // prevent error: "-Dmaven.multiModuleProjectDirectory system property is not set."
        System.setProperty("maven.multiModuleProjectDirectory", mavenProjectDir);

        // provide a local repo for maven dependencies
        String[] cliArgs = {"-Dmaven.repo.local=" + repo.getAbsolutePath(), "clean", "verify"};

        System.exit(cli.doMain(cliArgs, mavenProjectDir, System.out, System.err));
    }
}
